#!/usr/bin/env bash
set -euo pipefail

APP_DIR="/opt/aduc_for_linux"
REQ_FILE="${APP_DIR}/requirements.txt"
VENV_DIR="${APP_DIR}/venv"

python3 -m venv "${VENV_DIR}"
"${VENV_DIR}/bin/python" -m pip install --upgrade pip
"${VENV_DIR}/bin/pip" install -r "${REQ_FILE}"

exit 0
